apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-colors
  namespace: openshift-gitops
spec:
  destination:
    namespace: helm-colors
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: helm-colors
    repoURL: 'https://github.com/tal-hason/helm-colors-demo.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

