{{- range .Values.deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: helm-colors
    app.kubernetes.io/part-of: helm-colors
    app.kubernetes.io/instance: helm-colors
    app.kubernetes.io/name: helm-colors
    app: {{ .name }}
  name: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - image: quay.io/rhdevelopers/bgd:1.0.0
        name: {{ .name }}
        env:
        - name: COLOR
          value: {{ .color }}
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
{{- end }}